### ISSUE TITLE
Rename `Notes` enum to `BaseNote`

### ISSUE THREAD

**Issue by albertms10** [albertms10/music_notes#109]
## Description

- Rename `Notes` → `NoteName` or `BaseNote` and related class members and variables.
- (optional) Rename `Note` → `NoteSpelling` and related class members and variables.

### Example

Before:

```dart
Note(Notes.b, Accidental.sharp).note
```

After:

```dart
Note(BaseNote.b, Accidental.sharp).baseNote
```

### Advantages

- Clearer class intent.

### Drawbacks

- Longer names.

## Acknowledgements

@plammens for suggesting the change.

**Comment by plammens** [comment]
I don't know wheteher if it's already implied, but I would also add renaming all of the relevant variables/fields: `Note`'s `note` should become `baseNote` (so that `note.note` -> `note.baseNote`), etc.

**Comment by albertms10** [comment]
Sure, thanks for the clarification!
