### ISSUE TITLE
`Note.transposeBy` should return sharp accidentals for ascending intervals

### ISSUE THREAD

**Issue by heyaphra** [albertms10/music_notes#282]
First off, I just have to say that this is an excellent library for computational music research, so thank you for maintaining it! 

I'm running into this issue where I am getting flattened notes when transposing a note by intervals in an ascending scale. Re-spelling it upwards returns the note re-spelled as a doubly flattened, whereas re-spelling it downwards yields the result I was originally looking for. Is this expected behavior?

```dart
  var fundamental = Note.c;

  var ascendingChromaticScale = ScalePattern.chromatic.on(fundamental).degrees;
  // -> [C, C♯, D, D♯, E, F, F♯, G, G♯, A, A♯, B, C]

  var ascendingChromaticScaleIntervals = ScalePattern.chromatic.intervalSteps;
  // -> [A1, m2, A1, m2, m2, A1, m2, A1, m2, A1, m2, m2]

  print(fundamental.transposeBy(ascendingChromaticScaleIntervals[1]));
  // -> D♭

  print(fundamental.transposeBy(ascendingChromaticScaleIntervals[1]).respelledUpwards);
  // -> E♭𝄫

  print(fundamental.transposeBy(ascendingChromaticScaleIntervals[1]).respelledDownwards);
  // -> C♯
```

**Comment by heyaphra** [comment]
Feel free to close this issue, as I think there was a problem in my code. I transposed a scale note instead of `fundamental` (defined outside of the scale) and everything seems to work.

```dart
  var chromaticScaleNotes = ScalePattern.chromatic.on(fundamental).degrees;
  // -> [C, C♯, D, D♯, E, F, F♯, G, G♯, A, A♯, B, C]

  var chromaticScaleIntervals = ScalePattern.chromatic.intervalSteps;
  // -> [A1, m2, A1, m2, m2, A1, m2, A1, m2, A1, m2, m2]

  var maximalNote = chromaticScaleNotes[cycle].transposeBy(chromaticScaleIntervals[cycle]);

  print(maximalNote);
```

**Comment by albertms10** [comment]
@heyaphra! Thanks for your kind words! I appreciate your time coding with this library. 😸

Sure, I think the problem was you were accessing the second element by index `[1]` instead of the first one, so the Interval was not the one you might have expected. Happy to hear you figured it out!
